/*
 * File: app/view/ui/MinMaxSliderContainer.js
 * Date: Thu Feb 02 2012 11:22:47 GMT-0500 (Eastern Standard Time)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Mvpc.view.ui.MinMaxSliderContainer', {
    extend: 'Ext.container.Container',

    width: 260,
    layout: {
        type: 'column'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    itemId: 'histogramContainer'
                },
                {
                    xtype: 'container',
                    itemId: 'sliderContainer',
                    margin: '0 0 0 10',
                    width: 230
                },
                {
                    xtype: 'container',
                    itemId: 'minmaxContainer',
                    margin: '0 0 0 5',
                    width: 230,
                    layout: {
                        align: 'middle',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            itemId: 'minBox',
                            width: 100,
                            allowBlank: false,
                            margins: '0 0 0 5'
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'maxBox',
                            width: 100,
                            allowBlank: false,
                            margins: '0 0 10 10'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }
});