insert into CoverageSpectral values ('Radio')
insert into CoverageSpectral values ('Infrared')
insert into CoverageSpectral values ('Optical')
insert into CoverageSpectral values ('UV')
insert into CoverageSpectral values ('EUV')
insert into CoverageSpectral values ('X-Ray')
insert into CoverageSpectral values ('Gamma-ray')

insert into ContentLevel values ('General')
insert into ContentLevel values ('Elementary Education')
insert into ContentLevel values ('Middle School Education')
insert into ContentLevel values ('Secondary Education')
insert into ContentLevel values ('University')
insert into ContentLevel values ('Research')
insert into ContentLevel values ('Amateur')

insert into ResourceType values ('Archive')
insert into ResourceType values ('Survey')
insert into ResourceType values ('Catalog')
insert into ResourceType values ('Bibliography')
insert into ResourceType values ('Journal')
insert into ResourceType values ('Library')
insert into ResourceType values ('Outreach')
insert into ResourceType values ('Education')
insert into ResourceType values ('EPOResource')
insert into ResourceType values ('Other')