/*
 * File: app/view/ui/AstroViewContainer.js
 * Date: Tue Dec 13 2011 15:29:39 GMT-0500 (Eastern Standard Time)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Mvpc.view.ui.AstroViewContainer', {
    extend: 'Ext.container.Container',

    itemId: 'astroViewContainer',
    layout: {
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    }
});