//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://stsci.tap/TapConfiguration.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://stsci.tap/TapConfiguration.xsd", IsNullable=false)]
public partial class TAPServiceConfiguration {
    
    private TAPServiceConfigurationDatabase[] databaseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Database")]
    public TAPServiceConfigurationDatabase[] Database {
        get {
            return this.databaseField;
        }
        set {
            this.databaseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://stsci.tap/TapConfiguration.xsd")]
public partial class TAPServiceConfigurationDatabase {
    
    private TAPServiceConfigurationDatabaseTable[] tableField;
    
    private string nameField;
    
    private string connectionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Table")]
    public TAPServiceConfigurationDatabaseTable[] Table {
        get {
            return this.tableField;
        }
        set {
            this.tableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string connection {
        get {
            return this.connectionField;
        }
        set {
            this.connectionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://stsci.tap/TapConfiguration.xsd")]
public partial class TAPServiceConfigurationDatabaseTable {
    
    private string descriptionField;
    
    private TAPServiceConfigurationDatabaseTableColumn[] columnField;
    
    private TAPServiceConfigurationDatabaseTablePositionData positionDataField;
    
    private string nameField;
    
    private string typeField;
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Column")]
    public TAPServiceConfigurationDatabaseTableColumn[] Column {
        get {
            return this.columnField;
        }
        set {
            this.columnField = value;
        }
    }
    
    /// <remarks/>
    public TAPServiceConfigurationDatabaseTablePositionData PositionData {
        get {
            return this.positionDataField;
        }
        set {
            this.positionDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://stsci.tap/TapConfiguration.xsd")]
public partial class TAPServiceConfigurationDatabaseTableColumn {
    
    private string descriptionField;
    
    private string datatypeField;
    
    private string arraysizeField;
    
    private string unitField;
    
    private bool primaryField;
    
    private bool indexedField;
    
    private string nameField;
    
    private bool stdField;
    
    public TAPServiceConfigurationDatabaseTableColumn() {
        this.primaryField = false;
        this.indexedField = false;
        this.stdField = false;
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string datatype {
        get {
            return this.datatypeField;
        }
        set {
            this.datatypeField = value;
        }
    }
    
    /// <remarks/>
    public string arraysize {
        get {
            return this.arraysizeField;
        }
        set {
            this.arraysizeField = value;
        }
    }
    
    /// <remarks/>
    public string Unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool primary {
        get {
            return this.primaryField;
        }
        set {
            this.primaryField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool indexed {
        get {
            return this.indexedField;
        }
        set {
            this.indexedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool std {
        get {
            return this.stdField;
        }
        set {
            this.stdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://stsci.tap/TapConfiguration.xsd")]
public partial class TAPServiceConfigurationDatabaseTablePositionData {
    
    private TAPServiceConfigurationDatabaseTablePositionDataRA raField;
    
    private TAPServiceConfigurationDatabaseTablePositionDataDEC dECField;
    
    /// <remarks/>
    public TAPServiceConfigurationDatabaseTablePositionDataRA RA {
        get {
            return this.raField;
        }
        set {
            this.raField = value;
        }
    }
    
    /// <remarks/>
    public TAPServiceConfigurationDatabaseTablePositionDataDEC DEC {
        get {
            return this.dECField;
        }
        set {
            this.dECField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://stsci.tap/TapConfiguration.xsd")]
public partial class TAPServiceConfigurationDatabaseTablePositionDataRA {
    
    private string columnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Column {
        get {
            return this.columnField;
        }
        set {
            this.columnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://stsci.tap/TapConfiguration.xsd")]
public partial class TAPServiceConfigurationDatabaseTablePositionDataDEC {
    
    private string columnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Column {
        get {
            return this.columnField;
        }
        set {
            this.columnField = value;
        }
    }
}
