<h3> Welcome to the new NVO DataScope </h3>
<p>The NVO DataScope has been completely re-engineered to
give quicker results and more convenient access. After you start a 
query in just a few seconds you should get a page with a set
of tabbed panels that show all the results found in an easily
navigable form.  Just click on the panel tab to view that
panel.  If you have comments or suggestions send us
<a href="mailto:feedback@us-vo.org"> feedback</a>.
</p>
<hr />
