/*
 * File: app/view/ChartCanvasContainer.js
 * Date: Thu Aug 30 2012 09:41:05 GMT-0400 (Eastern Daylight Time)
 *
 * This file was generated by Ext Designer version 1.2.3.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('Mvpc.view.ChartCanvasContainer', {
    extend: 'Mvpc.view.ui.ChartCanvasContainer',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    },

    constructor: function (config) {
        this.callParent(arguments);
        this.store = config.store;
        this.facets = config.facets;
        delete config.facets;


        this.numericFacets = [];
        for (var i in this.facets) {
            var facet = this.facets[i];
            var text = facet.niceName || i;
            if (facet.chartType == 'Numeric') {
                this.numericFacets.push({title: text, unit: facet.unit, index: facet.index, key: i});
            }
        }
        this.dataArray = [];
        for (var i = 0; i < this.numericFacets.length; i++) {
            this.dataArray.push([]);
            this.key = this.numericFacets[i].key;
            this.store.backingStore.each(function (record) {
                this.dataArray[i].push(record.get(this.key));
            }, this);
        }

        this.data = new plotData(this.subtitle, this.dataArray, this.numericFacets, 0, 1);
        //this.replot(window.plot);
    },

    init: function() {
        this.plots = [];
        window.plot = new webplot('thePlot');
        this.addPlot(window.plot);
    },

    addPlot: function (plot) {
        this.plots.push(plot);
        if (this.data) this.replot(plot);
    },

    replotAll: function() {
        for (i = 0; i < this.plots.length; i++) {
            this.replot(this.plots[i]);
        }
    },
    
    replot: function(plot) {
        window.plot.setData(this.data);
        window.plot.showAllData();
        window.plot.redraw(); 
    }
});