/*
 * File: app/view/ui/CatalogDetailsContainer.js
 * Date: Fri Aug 31 2012 14:41:14 GMT-0400 (Eastern Daylight Time)
 *
 * This file was generated by Ext Designer version 1.2.3.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Mvpc.view.ui.CatalogDetailsContainer', {
    extend: 'Ext.container.Container',

    height: 200,
    itemId: 'catalogDetailsContainer',
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    itemId: 'summaryPanel',
                    autoScroll: true,
                    maintainFlex: true,
                    collapseFirst: false,
                    collapsed: false,
                    title: 'Summary',
                    region: 'center',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            height: 30,
                            itemId: 'detailsToolbar',
                            maintainFlex: true,
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    itemId:'loadButton',
                                    text: '<span style="font-size: 12px">Continue to Data</span>',
                                    style: 'border: 1px solid #000000;',
                                    margin: '0 1 0 1'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'downloadButton',
                                    text: '<span style="font-size: 12px">Download Data</span>',
                                    style: 'border: 1px solid #000000;',
                                    margin: '0 1 0 1'
                                }
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            height: 30,
                            itemId: 'searchToolbar',
                            maintainFlex: true,
                            dock: 'bottom'
                        }
                    ],
                    items: [
                        {
                            xtype: 'container',
                            height: 270,
                            itemId: 'summaryContainer',
                            maintainFlex: true,
                            layout: {
                                type: 'anchor'
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    height: 280,
                    itemId: 'detailsPanel',
                    layout: {
                        type: 'fit'
                    },
                    collapseDirection: 'bottom',
                    collapsed: true,
                    collapsible: true,
                    title: 'Expand for Details',
                    floatable: false,
                    region: 'south'
                }
            ]
        });

        me.callParent(arguments);
    }
});