/*
 * File: app/view/ui/MinMaxSliderContainer.js
 * Date: Thu Aug 09 2012 16:40:29 GMT-0400 (Eastern Daylight Time)
 *
 * This file was generated by Ext Designer version 1.2.3.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Mvpc.view.ui.MinMaxSliderContainer', {
    extend: 'Ext.form.FieldSet',

    width: 275,
    collapsed: true,
    collapsible: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    itemId: 'histogramContainer'
                },
                {
                    xtype: 'container',
                    itemId: 'sliderContainer',
                    margin: '0 0 0 10',
                    width: 260
                },
                {
                    xtype: 'container',
                    itemId: 'minmaxContainer',
                    margin: '0 0 0 5',
                    width: 255,
                    layout: {
                        pack: 'center',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            itemId: 'minBox',
                            width: 112,
                            allowBlank: false,
                            margins: '0 0 0 5'
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'maxBox',
                            width: 112,
                            allowBlank: false,
                            margins: '0 10 10 5'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    itemId: 'buttonContainer',
                    layout: {
                        pack: 'center',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'button',
                            disabled: true,
                            itemId: 'zoomButton',
                            text: 'Zoom to Range'
                        },
                        {
                            xtype: 'button',
                            itemId: 'resetButton',
                            text: 'Reset/Unzoom',
                            flex: 0,
                            margins: '0 0 0 10'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }
});