/*
 * File: app/view/ui/NedSedDetails.js
 * Date: Wed Dec 07 2011 12:52:45 GMT-0500 (EST)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Mvpc.view.ui.NedSedDetails', {
    extend: 'Ext.container.Container',

    height: 600,
    itemId: 'catalogDetailsContainer',
    width: 400,
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    itemId: 'summaryPanel',
                    autoScroll: true,
                    maintainFlex: true,
                    bodyPadding: 2,
                    collapseFirst: false,
                    collapsed: false,
                    title: 'Summary',
                    region: 'center',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            height: 30,
                            itemId: 'detailsToolbar',
                            maintainFlex: true,
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'loadButton',
                                    text: 'Load'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'downloadButton',
                                    text: 'Download'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'sampBroadcast',
                                    text: 'Broadcast (SAMP)'
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'container',
                            height: 270,
                            itemId: 'summaryContainer',
                            maintainFlex: true,
                            layout: {
                                type: 'anchor'
                            },
                            items: [
                                {
                                    xtype: 'displayfield',
                                    itemId: 'objectName',
                                    value: 'Display Field',
                                    fieldLabel: 'Object Name',
                                    labelWidth: 175,
                                    anchor: '100%'
                                },
                                {
                                    xtype: 'displayfield',
                                    itemId: 'numberOfPoints',
                                    value: 'Display Field',
                                    fieldLabel: 'Number of Photometric Points',
                                    labelWidth: 175,
                                    anchor: '100%'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    height: 280,
                    itemId: 'detailsPanel',
                    layout: {
                        type: 'fit'
                    },
                    collapseDirection: 'bottom',
                    collapsed: true,
                    collapsible: true,
                    title: 'Expand for Details',
                    floatable: false,
                    region: 'south'
                }
            ]
        });

        me.callParent(arguments);
    }
});