/*
 * File: app/view/ui/SiaDetailsContainer.js
 * Date: Mon Feb 27 2012 15:51:51 GMT-0500 (Eastern Standard Time)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Mvpc.view.ui.SiaDetailsContainer', {
    extend: 'Ext.container.Container',

    itemId: 'catalogDetailsContainer',
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    itemId: 'summaryPanel',
                    autoScroll: true,
                    maintainFlex: true,
                    bodyPadding: 2,
                    collapseFirst: false,
                    collapsed: false,
                    title: 'Summary',
                    region: 'center',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            height: 30,
                            itemId: 'detailsToolbar',
                            maintainFlex: true,
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'downloadButton',
                                    text: 'Download File'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'sampBroadcast',
                                    text: 'Broadcast (SAMP)'
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'container',
                            height: 270,
                            itemId: 'summaryContainer',
                            maintainFlex: true,
                            layout: {
                                type: 'anchor'
                            },
                            items: [
                                {
                                    xtype: 'displayfield',
                                    itemId: 'imageTitle',
                                    value: 'Display Field',
                                    fieldLabel: 'Image Title',
                                    anchor: '100%'
                                },
                                {
                                    xtype: 'displayfield',
                                    itemId: 'imageFormat',
                                    value: 'Display Field',
                                    fieldLabel: 'Image Format',
                                    anchor: '100%'
                                },
                                {
                                    xtype: 'fieldset',
                                    itemId: 'fieldOfView',
                                    style: '{font-size: \'16px\'}',
                                    title: 'Field of View Details',
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            itemId: 'centerRa',
                                            value: 'Display Field',
                                            fieldLabel: 'Center RA (degress)',
                                            labelWidth: 150,
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'displayfield',
                                            itemId: 'centerDec',
                                            value: 'Display Field',
                                            fieldLabel: 'Center Dec (degrees)',
                                            labelWidth: 150,
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'displayfield',
                                            itemId: 'imageExtent',
                                            value: 'Display Field',
                                            fieldLabel: 'Image Extent (arcmin)',
                                            labelWidth: 150,
                                            anchor: '100%'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    height: 280,
                    itemId: 'detailsPanel',
                    layout: {
                        type: 'fit'
                    },
                    collapseDirection: 'bottom',
                    collapsed: true,
                    collapsible: true,
                    title: 'Expand for Details',
                    floatable: false,
                    region: 'south'
                }
            ]
        });

        me.callParent(arguments);
    }
});