//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3607
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/UWS/v1.0")]
[System.Xml.Serialization.XmlRootAttribute("job", Namespace="http://www.ivoa.net/xml/UWS/v1.0", IsNullable=false)]
public partial class JobSummary {
    
    private string jobIdField;
    
    private string runIdField;
    
    private string ownerIdField;
    
    private ExecutionPhase phaseField;
    
    private System.Nullable<System.DateTime> quoteField;
    
    private bool quoteFieldSpecified;
    
    private System.Nullable<System.DateTime> startTimeField;
    
    private System.Nullable<System.DateTime> endTimeField;
    
    private int executionDurationField;
    
    private System.Nullable<System.DateTime> destructionField;
    
    private Parameter[] parametersField;
    
    private ResultReference[] resultsField;
    
    private ErrorSummary errorSummaryField;
    
    private JobSummaryJobInfo jobInfoField;
    
    /// <remarks/>
    public string jobId {
        get {
            return this.jobIdField;
        }
        set {
            this.jobIdField = value;
        }
    }
    
    /// <remarks/>
    public string runId {
        get {
            return this.runIdField;
        }
        set {
            this.runIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ownerId {
        get {
            return this.ownerIdField;
        }
        set {
            this.ownerIdField = value;
        }
    }
    
    /// <remarks/>
    public ExecutionPhase phase {
        get {
            return this.phaseField;
        }
        set {
            this.phaseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> quote {
        get {
            return this.quoteField;
        }
        set {
            this.quoteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool quoteSpecified {
        get {
            return this.quoteFieldSpecified;
        }
        set {
            this.quoteFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> startTime {
        get {
            return this.startTimeField;
        }
        set {
            this.startTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> endTime {
        get {
            return this.endTimeField;
        }
        set {
            this.endTimeField = value;
        }
    }
    
    /// <remarks/>
    public int executionDuration {
        get {
            return this.executionDurationField;
        }
        set {
            this.executionDurationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> destruction {
        get {
            return this.destructionField;
        }
        set {
            this.destructionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("parameter", IsNullable=false)]
    public Parameter[] parameters {
        get {
            return this.parametersField;
        }
        set {
            this.parametersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("result", IsNullable=false)]
    public ResultReference[] results {
        get {
            return this.resultsField;
        }
        set {
            this.resultsField = value;
        }
    }
    
    /// <remarks/>
    public ErrorSummary errorSummary {
        get {
            return this.errorSummaryField;
        }
        set {
            this.errorSummaryField = value;
        }
    }
    
    /// <remarks/>
    public JobSummaryJobInfo jobInfo {
        get {
            return this.jobInfoField;
        }
        set {
            this.jobInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/UWS/v1.0")]
public enum ExecutionPhase {
    
    /// <remarks/>
    PENDING,
    
    /// <remarks/>
    QUEUED,
    
    /// <remarks/>
    EXECUTING,
    
    /// <remarks/>
    COMPLETED,
    
    /// <remarks/>
    ERROR,
    
    /// <remarks/>
    UNKNOWN,
    
    /// <remarks/>
    HELD,
    
    /// <remarks/>
    SUSPENDED,
    
    /// <remarks/>
    ABORTED,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/UWS/v1.0")]
public partial class Parameter {
    
    private bool byReferenceField;
    
    private string idField;
    
    private bool isPostField;
    
    private bool isPostFieldSpecified;
    
    private string[] textField;
    
    public Parameter() {
        this.byReferenceField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool byReference {
        get {
            return this.byReferenceField;
        }
        set {
            this.byReferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool isPost {
        get {
            return this.isPostField;
        }
        set {
            this.isPostField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool isPostSpecified {
        get {
            return this.isPostFieldSpecified;
        }
        set {
            this.isPostFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/UWS/v1.0")]
public partial class ShortJobDescription {
    
    private ExecutionPhase phaseField;
    
    private string idField;
    
    private string hrefField;
    
    /// <remarks/>
    public ExecutionPhase phase {
        get {
            return this.phaseField;
        }
        set {
            this.phaseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink", DataType="anyURI")]
    public string href {
        get {
            return this.hrefField;
        }
        set {
            this.hrefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/UWS/v1.0")]
public partial class ErrorSummary {
    
    private string messageField;
    
    private ErrorType typeField;
    
    private bool hasDetailField;
    
    /// <remarks/>
    public string message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ErrorType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool hasDetail {
        get {
            return this.hasDetailField;
        }
        set {
            this.hasDetailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/UWS/v1.0")]
public enum ErrorType {
    
    /// <remarks/>
    transient,
    
    /// <remarks/>
    fatal,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/UWS/v1.0")]
public partial class ResultReference {
    
    private string idField;
    
    private string hrefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink", DataType="anyURI")]
    public string href {
        get {
            return this.hrefField;
        }
        set {
            this.hrefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ivoa.net/xml/UWS/v1.0")]
public partial class JobSummaryJobInfo {
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ivoa.net/xml/UWS/v1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/UWS/v1.0", IsNullable=false)]
public partial class jobs {
    
    private ShortJobDescription[] jobrefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("jobref")]
    public ShortJobDescription[] jobref {
        get {
            return this.jobrefField;
        }
        set {
            this.jobrefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ivoa.net/xml/UWS/v1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/UWS/v1.0", IsNullable=false)]
public partial class results {
    
    private ResultReference[] resultField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("result")]
    public ResultReference[] result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ivoa.net/xml/UWS/v1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/UWS/v1.0", IsNullable=false)]
public partial class parameters {
    
    private Parameter[] parameterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("parameter")]
    public Parameter[] parameter {
        get {
            return this.parameterField;
        }
        set {
            this.parameterField = value;
        }
    }
}
