/*
 * File: app/view/ui/CaomDetailsContainer.js
 * Date: Thu Nov 29 2012 10:15:46 GMT-0500 (Eastern Standard Time)
 *
 * This file was generated by Ext Designer version 1.2.3.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Mvpc.view.ui.CaomDetailsContainer', {
    extend: 'Ext.container.Container',

    itemId: 'caomDetailsContainer',
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    itemId: 'summaryPanel',
                    autoScroll: true,
                    collapsed: false,
                    title: 'Summary',
                    region: 'center',
                    items: [
                        {
                            xtype: 'container',
                            height: 50,
                            itemId: 'titleContainer',
                            margin: '10 0 0 0',
                            layout: {
                                type: 'anchor'
                            }
                        },
                        {
                            xtype: 'container',
                            height: 260,
                            itemId: 'imageContainer',
                            margin: '10 0 0 0',
                            padding: 2,
                            maintainFlex: true,
                            layout: {
                                type: 'anchor'
                            }
                        },
                        {
                            xtype: 'container',
                            height: 170,
                            itemId: 'summaryContainer',
                            margin: '10 5 0 5',
                            layout: {
                                align: 'center',
                                type: 'vbox'
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    height: 250,
                    itemId: 'detailsPanel',
                    layout: {
                        type: 'fit'
                    },
                    collapsed: true,
                    collapsible: true,
                    title: 'Expand for Details',
                    floatable: false,
                    region: 'south'
                }
            ]
        });

        me.callParent(arguments);
    }
});