/*
 * File: app/view/ui/LayerChooserContainer.js
 * Date: Mon Apr 23 2012 14:04:33 GMT-0400 (Eastern Daylight Time)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Mvpc.view.ui.LayerChooserContainer', {
    extend: 'Ext.container.Container',


    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'checkboxfield',
                    itemId: 'layerCheckbox',
                    style: {
                        'font-size': '11px',
                        'font-family': 'helvetica,tahoma,verdana,sans-serif'
                    },
                    boxLabel: 'AstroView Display',
                    boxLabelAlign: 'before'
                }
            ]
        });

        me.callParent(arguments);
    }
});