/**
 * Copyright (C) Smithsonian Astrophysical Observatory
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package cfa.vo.utils;


public class Sesame_sesame_sesameRequest2_sesameResponse2_RequestStruct {
    protected java.lang.String name;
    protected java.lang.String resultType;
    protected boolean all;
    protected java.lang.String service;
    
    public Sesame_sesame_sesameRequest2_sesameResponse2_RequestStruct() {
    }
    
    public Sesame_sesame_sesameRequest2_sesameResponse2_RequestStruct(java.lang.String name, java.lang.String resultType, boolean all, java.lang.String service) {
        this.name = name;
        this.resultType = resultType;
        this.all = all;
        this.service = service;
    }
    
    public java.lang.String getName() {
        return name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public java.lang.String getResultType() {
        return resultType;
    }
    
    public void setResultType(java.lang.String resultType) {
        this.resultType = resultType;
    }
    
    public boolean isAll() {
        return all;
    }
    
    public void setAll(boolean all) {
        this.all = all;
    }
    
    public java.lang.String getService() {
        return service;
    }
    
    public void setService(java.lang.String service) {
        this.service = service;
    }
}
