<table width='100%'><tr><td width='15%'></td><td width='70%'>
<h1> Search a position for all known information</h1>
Use DataScope to find everything that's known about a given target or region of the sky.
DataScope will query hundreds of VO-enabled data resources and organize the
results for your viewing.  <em>New in version 4</em>: Additional resources now being searched,
which can (among other things) significantly increase the number of Vizier catalogs found.
</td><td width='15%'></tr>
<tr><td></td><td><p><p><p></td><td></td></tr>
</table>
