#! /usr/bin/env python

import vaologin.cli.portalcgi

# Uncomment this line and set the value to the full path to the 
# configuration file.  See docs for info on default locations used 
# when this is not set.
# 
# vaologin.cli.portalcgi.configfile = "/etc/httpd/conf/vaologin.cfg"

# see main() in vaologin/cli/portal.py for script implementation
from vaologin.cli.portalcgi import main
from vaologin.cli.utils import run

run(main)
