//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
// http://www.ivoa.net/xml/VOTable/v1.1
// http://www.ivoa.net/xml/VOTable/v1.1
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.573.
// 
using System.Xml.Serialization;
namespace net.ivoa.VOTable 
{

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
	public class VOTABLE 
	{
    
		/// <remarks/>
		public anyTEXT DESCRIPTION;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute(typeof(COOSYS), IsNullable=false)]
		[System.Xml.Serialization.XmlArrayItemAttribute(typeof(PARAM), IsNullable=false)]
		public object[] DEFINITIONS;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("INFO")]
		public INFO[] INFO;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("RESOURCE")]
		public RESOURCE[] RESOURCE;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
		public string ID;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public VOTABLEVersion version;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool versionSpecified;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	[System.Xml.Serialization.XmlRootAttribute("DESCRIPTION", Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
	public class anyTEXT 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		[System.Xml.Serialization.XmlAnyElementAttribute()]
		public System.Xml.XmlNode[] Any;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
	public class FITS 
	{
    
		/// <remarks/>
		public STREAM STREAM;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
		public string extnum;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
	public class STREAM 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(STREAMType.locator)]
		public STREAMType type = STREAMType.locator;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
		public string href;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(STREAMActuate.onRequest)]
		public STREAMActuate actuate = STREAMActuate.onRequest;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(encodingType.none)]
		public encodingType encoding = encodingType.none;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public System.DateTime expires;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool expiresSpecified;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
		public string rights;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	public enum STREAMType 
	{
    
		/// <remarks/>
		locator,
    
		/// <remarks/>
		other,
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	public enum STREAMActuate 
	{
    
		/// <remarks/>
		onLoad,
    
		/// <remarks/>
		onRequest,
    
		/// <remarks/>
		other,
    
		/// <remarks/>
		none,
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	public enum encodingType 
	{
    
		/// <remarks/>
		gzip,
    
		/// <remarks/>
		base64,
    
		/// <remarks/>
		dynamic,
    
		/// <remarks/>
		none,
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
	public class BINARY 
	{
    
		/// <remarks/>
		public STREAM STREAM;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
	public class TD 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public encodingType encoding;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool encodingSpecified;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string[] Text;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
	public class DATA 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("TABLEDATA", typeof(TABLEDATA))]
		[System.Xml.Serialization.XmlElementAttribute("FITS", typeof(FITS))]
		[System.Xml.Serialization.XmlElementAttribute("BINARY", typeof(BINARY))]
		public object Item;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
	public class PARAMref 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
		public string @ref;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
	public class FIELDref 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
		public string @ref;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
	public class GROUP 
	{
    
		/// <remarks/>
		public anyTEXT DESCRIPTION;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("PARAMref", typeof(PARAMref))]
		[System.Xml.Serialization.XmlElementAttribute("PARAM", typeof(PARAM))]
		[System.Xml.Serialization.XmlElementAttribute("FIELD", typeof(FIELD))]
		[System.Xml.Serialization.XmlElementAttribute("FIELDref", typeof(FIELDref))]
		[System.Xml.Serialization.XmlElementAttribute("GROUP", typeof(GROUP))]
		public object[] Items;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
		public string ID;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
		public string name;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
		public string @ref;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
		public string ucd;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string utype;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
	public class PARAM 
	{
    
		/// <remarks/>
		public anyTEXT DESCRIPTION;
    
		/// <remarks/>
		public VALUES VALUES;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("LINK")]
		public LINK[] LINK;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
		public string ID;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
		public string unit;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public dataType datatype;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
		public string precision;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
		public string width;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
		public string @ref;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
		public string name;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
		public string ucd;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string utype;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string value;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
		public string arraysize;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
	public class VALUES 
	{
    
		/// <remarks/>
		public MIN MIN;
    
		/// <remarks/>
		public MAX MAX;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("OPTION")]
		public OPTION[] OPTION;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
		public string ID;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(VALUESType.legal)]
		public VALUESType type = VALUESType.legal;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
		public string @null;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
		public string @ref;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
	public class MIN 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string value;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(yesno.yes)]
		public yesno inclusive = yesno.yes;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	public enum yesno 
	{
    
		/// <remarks/>
		yes,
    
		/// <remarks/>
		no,
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
	public class MAX 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string value;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(yesno.yes)]
		public yesno inclusive = yesno.yes;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
	public class OPTION 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("OPTION")]
		public OPTION[] OPTION1;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
		public string name;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string value;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	public enum VALUESType 
	{
    
		/// <remarks/>
		legal,
    
		/// <remarks/>
		actual,
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
	public class LINK 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
		public string ID;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute("content-role")]
		public LINKContentrole contentrole;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool contentroleSpecified;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute("content-type", DataType="token")]
		public string contenttype;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string title;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string value;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
		public string href;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
		public string gref;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
		public string action;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string[] Text;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	public enum LINKContentrole 
	{
    
		/// <remarks/>
		query,
    
		/// <remarks/>
		hints,
    
		/// <remarks/>
		doc,
    
		/// <remarks/>
		location,
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	public enum dataType 
	{
    
		/// <remarks/>
		boolean,
    
		/// <remarks/>
		bit,
    
		/// <remarks/>
		unsignedByte,
    
		/// <remarks/>
		@short,
    
		/// <remarks/>
		@int,
    
		/// <remarks/>
		@long,
    
		/// <remarks/>
		@char,
    
		/// <remarks/>
		unicodeChar,
    
		/// <remarks/>
		@float,
    
		/// <remarks/>
		@double,
    
		/// <remarks/>
		floatComplex,
    
		/// <remarks/>
		doubleComplex,
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
	public class FIELD 
	{
    
		/// <remarks/>
		public anyTEXT DESCRIPTION;
    
		/// <remarks/>
		public VALUES VALUES;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("LINK")]
		public LINK[] LINK;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
		public string ID;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
		public string unit;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public dataType datatype;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
		public string precision;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
		public string width;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
		public string @ref;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
		public string name;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
		public string ucd;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string utype;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string arraysize;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
	public class TABLE 
	{
    
		/// <remarks/>
		public anyTEXT DESCRIPTION;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("PARAM", typeof(PARAM))]
		[System.Xml.Serialization.XmlElementAttribute("FIELD", typeof(FIELD))]
		[System.Xml.Serialization.XmlElementAttribute("GROUP", typeof(GROUP))]
		public object[] Items;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("LINK")]
		public LINK[] LINK;
    
		/// <remarks/>
		public DATA DATA;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
		public string ID;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
		public string name;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
		public string @ref;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
	public class RESOURCE 
	{
    
		/// <remarks/>
		public anyTEXT DESCRIPTION;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("COOSYS", typeof(COOSYS))]
		[System.Xml.Serialization.XmlElementAttribute("INFO", typeof(INFO))]
		[System.Xml.Serialization.XmlElementAttribute("PARAM", typeof(PARAM))]
		public object[] Items;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("LINK")]
		public LINK[] LINK;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("TABLE")]
		public TABLE[] TABLE;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("RESOURCE")]
		public RESOURCE[] RESOURCE1;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAnyElementAttribute()]
		public System.Xml.XmlElement[] Any;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
		public string name;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
		public string ID;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(RESOURCEType.results)]
		public RESOURCEType type = RESOURCEType.results;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAnyAttributeAttribute()]
		public System.Xml.XmlAttribute[] AnyAttr;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
	public class COOSYS 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
		public string ID;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
		public string equinox;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
		public string epoch;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(COOSYSSystem.eq_FK5)]
		public COOSYSSystem system = COOSYSSystem.eq_FK5;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string[] Text;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	public enum COOSYSSystem 
	{
    
		/// <remarks/>
		eq_FK4,
    
		/// <remarks/>
		eq_FK5,
    
		/// <remarks/>
		ICRS,
    
		/// <remarks/>
		ecl_FK4,
    
		/// <remarks/>
		ecl_FK5,
    
		/// <remarks/>
		galactic,
    
		/// <remarks/>
		supergalactic,
    
		/// <remarks/>
		xy,
    
		/// <remarks/>
		barycentric,
    
		/// <remarks/>
		geo_app,
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
	public class INFO 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
		public string ID;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
		public string name;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string value;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string[] Text;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	public enum RESOURCEType 
	{
    
		/// <remarks/>
		results,
    
		/// <remarks/>
		meta,
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	public enum VOTABLEVersion 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("1.1")]
		Item11,
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
	public class DEFINITIONS 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("COOSYS", typeof(COOSYS))]
		[System.Xml.Serialization.XmlElementAttribute("PARAM", typeof(PARAM))]
		public object[] Items;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
	public class TABLEDATA 
	{
    
  
		[System.Xml.Serialization.XmlElementAttribute("TR")]
		public TR[] TR;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
	public class TR 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("TD")]
		public TD[] TD;
	}
}