//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace net.ivoa.VOTable {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
    public partial class VOTABLE {
        
        /// <remarks/>
        public anyTEXT DESCRIPTION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("COOSYS", typeof(COOSYS), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PARAM", typeof(PARAM), IsNullable=false)]
        public object[] DEFINITIONS;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("COOSYS", typeof(COOSYS))]
        [System.Xml.Serialization.XmlElementAttribute("INFO", typeof(INFO))]
        [System.Xml.Serialization.XmlElementAttribute("PARAM", typeof(PARAM))]
        public object[] Items;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RESOURCE")]
        public RESOURCE[] RESOURCE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public VOTABLEVersion version;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool versionSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum VOTABLEVersion {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.1")]
        Item11,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=false)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
    public partial class RESOURCE {
        
        /// <remarks/>
        public anyTEXT DESCRIPTION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("COOSYS", typeof(COOSYS))]
        [System.Xml.Serialization.XmlElementAttribute("INFO", typeof(INFO))]
        [System.Xml.Serialization.XmlElementAttribute("PARAM", typeof(PARAM))]
        public object[] Items;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LINK")]
        public LINK[] LINK;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TABLE")]
        public TABLE[] TABLE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RESOURCE")]
        public RESOURCE[] RESOURCE1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string utype;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(RESOURCEType.results)]
        public RESOURCEType type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr;
        
        public RESOURCE() {
            this.type = RESOURCEType.results;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum RESOURCEType {
        
        /// <remarks/>
        results,
        
        /// <remarks/>
        meta,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
    [System.Xml.Serialization.XmlRootAttribute("DESCRIPTION", Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
    public partial class anyTEXT {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
    public partial class DEFINITIONS {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("COOSYS", typeof(COOSYS))]
        [System.Xml.Serialization.XmlElementAttribute("PARAM", typeof(PARAM))]
        public object[] Items;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
    public partial class INFO {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
    public partial class PARAM {
        
        /// <remarks/>
        public anyTEXT DESCRIPTION;
        
        /// <remarks/>
        public VALUES VALUES;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LINK")]
        public LINK[] LINK;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string unit;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public dataType datatype;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string precision;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string width;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string @ref;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string ucd;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string utype;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string arraysize;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
    public enum dataType {
        
        /// <remarks/>
        boolean,
        
        /// <remarks/>
        bit,
        
        /// <remarks/>
        unsignedByte,
        
        /// <remarks/>
        @short,
        
        /// <remarks/>
        @int,
        
        /// <remarks/>
        @long,
        
        /// <remarks/>
        @char,
        
        /// <remarks/>
        unicodeChar,
        
        /// <remarks/>
        @float,
        
        /// <remarks/>
        @double,
        
        /// <remarks/>
        floatComplex,
        
        /// <remarks/>
        doubleComplex,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
    public partial class TABLE {
        
        /// <remarks/>
        public anyTEXT DESCRIPTION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FIELD", typeof(FIELD))]
        [System.Xml.Serialization.XmlElementAttribute("GROUP", typeof(GROUP))]
        [System.Xml.Serialization.XmlElementAttribute("PARAM", typeof(PARAM))]
        public object[] Items;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LINK")]
        public LINK[] LINK;
        
        /// <remarks/>
        public DATA DATA;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string @ref;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string ucd;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string utype;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string nrows;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
    public partial class FIELD {
        
        /// <remarks/>
        public anyTEXT DESCRIPTION;
        
        /// <remarks/>
        public VALUES VALUES;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LINK")]
        public LINK[] LINK;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string unit;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public dataType datatype;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string precision;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string width;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string @ref;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string ucd;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string utype;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string arraysize;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public FIELDType type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum FIELDType {
        
        /// <remarks/>
        hidden,
        
        /// <remarks/>
        no_query,
        
        /// <remarks/>
        trigger,
        
        /// <remarks/>
        location,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=false)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
    public partial class GROUP {
        
        /// <remarks/>
        public anyTEXT DESCRIPTION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FIELDref", typeof(FIELDref))]
        [System.Xml.Serialization.XmlElementAttribute("GROUP", typeof(GROUP))]
        [System.Xml.Serialization.XmlElementAttribute("PARAM", typeof(PARAM))]
        [System.Xml.Serialization.XmlElementAttribute("PARAMref", typeof(PARAMref))]
        public object[] Items;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string @ref;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string ucd;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string utype;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
    public partial class FIELDref {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string @ref;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
    public partial class PARAMref {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string @ref;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
    public partial class VALUES {
        
        /// <remarks/>
        public MIN MIN;
        
        /// <remarks/>
        public MAX MAX;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OPTION")]
        public OPTION[] OPTION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(VALUESType.legal)]
        public VALUESType type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string @null;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string @ref;
        
        public VALUES() {
            this.type = VALUESType.legal;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum VALUESType {
        
        /// <remarks/>
        legal,
        
        /// <remarks/>
        actual,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
    public partial class MIN {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(yesno.yes)]
        public yesno inclusive;
        
        public MIN() {
            this.inclusive = yesno.yes;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
    public enum yesno {
        
        /// <remarks/>
        yes,
        
        /// <remarks/>
        no,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
    public partial class MAX {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(yesno.yes)]
        public yesno inclusive;
        
        public MAX() {
            this.inclusive = yesno.yes;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=false)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
    public partial class OPTION {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OPTION")]
        public OPTION[] OPTION1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
    public partial class LINK {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("content-role")]
        public LINKContentrole contentrole;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool contentroleSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("content-type", DataType="token")]
        public string contenttype;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string href;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string gref;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string action;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum LINKContentrole {
        
        /// <remarks/>
        query,
        
        /// <remarks/>
        hints,
        
        /// <remarks/>
        doc,
        
        /// <remarks/>
        location,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
    public partial class DATA {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BINARY", typeof(BINARY))]
        [System.Xml.Serialization.XmlElementAttribute("FITS", typeof(FITS))]
        [System.Xml.Serialization.XmlElementAttribute("TABLEDATA", typeof(TABLEDATA))]
        public object Item;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
    public partial class TABLEDATA {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("TR", typeof(TR), IsNullable=false)]
        public TR[] TR;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
    public partial class TD {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public encodingType encoding;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool encodingSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1")]
    public enum encodingType {
        
        /// <remarks/>
        gzip,
        
        /// <remarks/>
        base64,
        
        /// <remarks/>
        dynamic,
        
        /// <remarks/>
        none,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
    public partial class TR {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TD")]
        public TD[] TD;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
    public partial class FITS {
        
        /// <remarks/>
        public STREAM STREAM;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string extnum;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
    public partial class BINARY {
        
        /// <remarks/>
        public STREAM STREAM;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
    public partial class STREAM {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(STREAMType.locator)]
        public STREAMType type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string href;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(STREAMActuate.onRequest)]
        public STREAMActuate actuate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(encodingType.none)]
        public encodingType encoding;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime expires;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expiresSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string rights;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
        
        public STREAM() {
            this.type = STREAMType.locator;
            this.actuate = STREAMActuate.onRequest;
            this.encoding = encodingType.none;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum STREAMType {
        
        /// <remarks/>
        locator,
        
        /// <remarks/>
        other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum STREAMActuate {
        
        /// <remarks/>
        onLoad,
        
        /// <remarks/>
        onRequest,
        
        /// <remarks/>
        other,
        
        /// <remarks/>
        none,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.1", IsNullable=false)]
    public partial class COOSYS {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string equinox;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string epoch;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(COOSYSSystem.eq_FK5)]
        public COOSYSSystem system;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
        
        public COOSYS() {
            this.system = COOSYSSystem.eq_FK5;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum COOSYSSystem {
        
        /// <remarks/>
        eq_FK4,
        
        /// <remarks/>
        eq_FK5,
        
        /// <remarks/>
        ICRS,
        
        /// <remarks/>
        ecl_FK4,
        
        /// <remarks/>
        ecl_FK5,
        
        /// <remarks/>
        galactic,
        
        /// <remarks/>
        supergalactic,
        
        /// <remarks/>
        xy,
        
        /// <remarks/>
        barycentric,
        
        /// <remarks/>
        geo_app,
    }
}
