/*
 * File: app/view/ui/CrossMatch.js
 * Date: Thu May 16 2013 11:08:05 GMT-0400 (EDT)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Mvpd.view.ui.CrossMatch', {
    extend: 'Ext.window.Window',

    autoRender: false,
    border: '',
    activeItem: 0,
    layout: {
        type: 'fit'
    },
    title: 'Cross-Match Table With...',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    border: '',
                    itemId: 'crossMatchPanel',
                    width: 360,
                    layout: {
                        type: 'anchor'
                    },
                    items: [
                        {
                            xtype: 'fieldset',
                            itemId: 'fileFieldset',
                            margin: '2 0 2 5',
                            width: 345,
                            title: 'File',
                            items: [
                                {
                                    xtype: 'form',
                                    border: 0,
                                    itemId: 'formPanel',
                                    width: 335,
                                    defaults: {
                                        margin: 10,
                                        labelWidth: 100
                                    },
                                    bodyPadding: 10,
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            itemId: 'CDSTablePulldown',
                                            fieldLabel: 'CDS Table',
                                            allowBlank: false,
                                            displayField: 'displayField',
                                            forceSelection: true,
                                            queryMode: 'local',
                                            store: 'CDSTableStore',
                                            valueField: 'valueField',
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'container',
                                            itemId: 'buttonContainer',
                                            layout: {
                                                align: 'middle',
                                                pack: 'center',
                                                type: 'hbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    itemId: 'xMatchButton',
                                                    margin: '5 10 0 5',
                                                    text: 'Cross-Match'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'cancelButton',
                                                    margin: '5 10 0 5',
                                                    text: 'Cancel'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }
});