/**
 * Copyright (C) Smithsonian Astrophysical Observatory
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package cfa.vo.utils;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;

public class Sesame_main_mainRequest_mainResponse_RequestStruct_SOAPSerializer extends ObjectSerializerBase implements Initializable {
    private static final javax.xml.namespace.QName ns1_in0_QNAME = new QName("", "in0");
    private static final javax.xml.namespace.QName ns3_ArrayOf_xsd_string_TYPE_QNAME = new QName("urn:Sesame", "ArrayOf_xsd_string");
    private CombinedSerializer ns3_myns3_ArrayOf_xsd_string__StringArray_SOAPSerializer1;
    private static final int myIN0_INDEX = 0;
    
    public Sesame_main_mainRequest_mainResponse_RequestStruct_SOAPSerializer(QName type, boolean encodeType, boolean isNullable, String encodingStyle) {
        super(type, encodeType, isNullable, encodingStyle);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws java.lang.Exception {
        ns3_myns3_ArrayOf_xsd_string__StringArray_SOAPSerializer1 = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, java.lang.String[].class, ns3_ArrayOf_xsd_string_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(SOAPDeserializationState state, XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        cfa.vo.utils.Sesame_main_mainRequest_mainResponse_RequestStruct instance = new cfa.vo.utils.Sesame_main_mainRequest_mainResponse_RequestStruct();
        cfa.vo.utils.Sesame_main_mainRequest_mainResponse_RequestStruct_SOAPBuilder builder = null;
        java.lang.Object member;
        boolean isComplete = true;
        javax.xml.namespace.QName elementName;
        
        reader.nextElementContent();
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_in0_QNAME)) {
                member = ns3_myns3_ArrayOf_xsd_string__StringArray_SOAPSerializer1.deserialize(ns1_in0_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new cfa.vo.utils.Sesame_main_mainRequest_mainResponse_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myIN0_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setIn0((java.lang.String[])member);
                }
                reader.nextElementContent();
            } else {
                throw new DeserializationException("soap.unexpectedElementName", new Object[] {ns1_in0_QNAME, elementName});
            }
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (isComplete ? (java.lang.Object)instance : (java.lang.Object)state);
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        cfa.vo.utils.Sesame_main_mainRequest_mainResponse_RequestStruct instance = (cfa.vo.utils.Sesame_main_mainRequest_mainResponse_RequestStruct)obj;
        
    }
    
    public void doSerializeInstance(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        cfa.vo.utils.Sesame_main_mainRequest_mainResponse_RequestStruct instance = (cfa.vo.utils.Sesame_main_mainRequest_mainResponse_RequestStruct)obj;
        
        ns3_myns3_ArrayOf_xsd_string__StringArray_SOAPSerializer1.serialize(instance.getIn0(), ns1_in0_QNAME, null, writer, context);
    }
}
