<p>
<b>Positions</b> may be entered in decimal (dd.f, sdd.f)
or sexagesimal (hh mm ss.f, dd mm ss.f) notation or as
targets recognized by NED or SIMBAD.
<p>
The <b>Size</b> should be entered in decimal degrees.
<p>
Use the <b>Skip cache</b> flag to ensure that you
get the latest results from all services.
<p>
By default the last few queries anyone has made are
shown at the bottom of the page but there is a checkbox
to keep your query from being recorded on this list.
<p>