//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3607
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/Availability/v0.4")]
[System.Xml.Serialization.XmlRootAttribute("availability", Namespace="http://www.ivoa.net/xml/Availability/v0.4", IsNullable=false)]
public partial class Availability {
    
    private bool availableField;
    
    private System.DateTime upSinceField;
    
    private bool upSinceFieldSpecified;
    
    private System.DateTime downAtField;
    
    private bool downAtFieldSpecified;
    
    private System.DateTime backAtField;
    
    private bool backAtFieldSpecified;
    
    private string[] noteField;
    
    /// <remarks/>
    public bool available {
        get {
            return this.availableField;
        }
        set {
            this.availableField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime upSince {
        get {
            return this.upSinceField;
        }
        set {
            this.upSinceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool upSinceSpecified {
        get {
            return this.upSinceFieldSpecified;
        }
        set {
            this.upSinceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime downAt {
        get {
            return this.downAtField;
        }
        set {
            this.downAtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool downAtSpecified {
        get {
            return this.downAtFieldSpecified;
        }
        set {
            this.downAtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime backAt {
        get {
            return this.backAtField;
        }
        set {
            this.backAtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool backAtSpecified {
        get {
            return this.backAtFieldSpecified;
        }
        set {
            this.backAtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("note")]
    public string[] note {
        get {
            return this.noteField;
        }
        set {
            this.noteField = value;
        }
    }
}
