/*
 * File: app/view/AstroViewContainer.js
 * Date: Tue Dec 13 2011 15:29:39 GMT-0500 (Eastern Standard Time)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('Mvpc.view.AstroViewContainer', {
    extend: 'Mvpc.view.ui.AstroViewContainer',

    initComponent: function () {
        var me = this;
        me.callParent(arguments);
    },

    constructor: function () {
        this.callParent(arguments);

        this.swf = Ext.create('Ext.flash.Component', {
            id: 'AstroView',
            url: '../AstroView/AstroView.swf'
        });

        this.add(this.swf);

        this.swf.on('success', this.onFlashSuccess, this);
    },

    onFlashSuccess: function () {
        this.swfId = this.swf.swfId;
    },
});