/*
 * File: app/view/ui/DatascopeDetailsContainer.js
 * Date: Fri Mar 22 2013 14:57:48 GMT-0400 (Eastern Daylight Time)
 *
 * This file was generated by Ext Designer version 1.2.3.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Mvpc.view.ui.DatascopeDetailsContainer', {
    extend: 'Ext.container.Container',

    height: 500,
    itemId: 'datascopeDetailsContainer',
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    itemId: 'summaryPanel',
                    autoScroll: true,
                    maintainFlex: true,
                    collapseFirst: false,
                    collapsed: false,
                    title: 'Summary',
                    region: 'center',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            height: 35,
                            itemId: 'detailsToolbar',
                            maintainFlex: true,
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'loadButton',
                                    margin: '0 1 0 1',
                                    icon: Mvp.util.Constants.GOTO_DATA_ICON[Mvp.util.Constants.ICON_SIZE],
                                    scale: Mvp.util.Constants.ICON_SIZE,
                                    tooltip: 'Continue to Data'
                                },
                                {
                                    xtype: 'tbseparator',
                                    itemId: 'separator1'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'downloadButton',
                                    margin: '0 1 0 1',
                                    icon: Mvp.util.Constants.SAVEAS_ICON[Mvp.util.Constants.ICON_SIZE],
                                    scale: Mvp.util.Constants.ICON_SIZE,
                                    tooltip: 'Download Resource XML'
                                },
                                {
                                    xtype: 'tbseparator',
                                    itemId: 'separator2'
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'container',
                            height: 270,
                            itemId: 'summaryContainer',
                            maintainFlex: true,
                            layout: {
                                type: 'anchor'
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    height: 280,
                    itemId: 'detailsPanel',
                    layout: {
                        type: 'fit'
                    },
                    collapseDirection: 'bottom',
                    collapsed: true,
                    collapsible: true,
                    title: 'Expand for Details',
                    floatable: false,
                    region: 'south'
                }
            ]
        });

        me.callParent(arguments);
    }
});