#!/bin/bash

# Copyright 2011 Smithsonian Astrophysical Observatory
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

args=""

#  Find where this script is located.

bindir=$( cd -P "$( dirname "$0" )" && pwd )
if [ -h "$0" ]; then
    bindir=$( cd -P "$( dirname "`readlink -n "$0"`" )" && pwd )
fi

export IRIS_DIR="$bindir"

sed_dir=\"$bindir/lib/importer\"

# Set location of acceptable jar file.
sed_jar=\"$bindir/lib/importer/SedImporter-1.0.jar\"

#JAVA=`which java`


if test -x /usr/bin/sw_vers && /usr/bin/sw_vers | grep -q 'OS.X'; then
    args="-Xdock:name=\"SED Importer\""

    MACJAVA="/System/Library/Frameworks/JavaVM.framework/Versions/1.6/Commands/java"

    if test ! -f "$MACJAVA"; then
	echo 1>&2 "Can't find Java 1.6 $MACJAVA"
	exit 1
    fi
    
    JAVA=$MACJAVA

fi

cmd="/www/htdocs/vo/java/jre/bin/java $args -jar $sed_jar $@ -Duser.home=/tmp.shared/vo/vaomonitor/irisplugins";
eval "$cmd"
