#!/bin/bash

prefix=/usr/local

bindir=${prefix}/bin/
libdir=${prefix}/lib/
incdir=${prefix}/include/
mandir=${prefix}/man/man1/

# Process cmdline flags.
for a in "$@"
do
    case "$a" in
    -b | -bindir | --bindir)        # task bin directory
        echo /tmp/bin/ ;;
    -l | -libdir | --libdir)        # library directory
        echo /tmp/lib/ ;;
    -i | -incdir | --incdir) 	    # include directory
        echo /tmp/include/ ;;
    -m | -mandir | --mandir)        # man page directory
        echo /tmp/man/man1/ ;;
    *)
	exit 1 ;;
    esac
done
