/*
* File: app/view/ui/registryDetailsContainer.js
* Date: Wed Dec 05 2012 09:34:02 GMT-0500 (Eastern Standard Time)
*
* This file was generated by Ext Designer version 1.2.3.
* http://www.sencha.com/products/designer/
*
* This file will be auto-generated each and everytime you export.
*
* Do NOT hand edit this file.
*/

Ext.define('Mvpc.view.ui.RegistryDetailsContainer', {
    extend: 'Ext.container.Container',

    itemId: 'registryDetailsContainer',
    layout: {
        type: 'border'
    },

    initComponent: function () {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    itemId: 'summaryPanel',
                    autoScroll: true,
                    maintainFlex: true,
                    collapseFirst: false,
                    collapsed: false,
                    title: 'Summary',
                    region: 'center',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            itemId: 'detailsToolbar',
                            maintainFlex: true,
                            dock: 'top',
                            items: [] //resource-type dependent, built conditionally on load.
                        },
                        {
                            xtype: 'toolbar',
                            itemId: 'searchToolbar',
                            maintainFlex: true,
                            dock: 'bottom'
                        }
                    ],
                    items: [
                        {
                            xtype: 'container',
                            height: 270,
                            itemId: 'summaryContainer',
                            maintainFlex: true,
                            layout: {
                                type: 'anchor'
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    height: 280,
                    itemId: 'detailsPanel',
                    layout: {
                        type: 'fit'
                    },
                    collapseDirection: 'bottom',
                    collapsed: true,
                    collapsible: true,
                    title: 'Expand for Details',
                    floatable: false,
                    region: 'south'
                }
            ]
        });

        me.callParent(arguments);
    }
});