/* confdefs.h */
#define PACKAGE_NAME "curl"
#define PACKAGE_TARNAME "curl"
#define PACKAGE_VERSION "-"
#define PACKAGE_STRING "curl -"
#define PACKAGE_BUGREPORT "a suitable curl mailing list: http://curl.haxx.se/mail/"
#define PACKAGE_URL ""
#define PACKAGE "curl"
#define VERSION "-"
#define OS "x86_64-apple-darwin13.0.0"
#define HAVE_SYS_TYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_INTTYPES_H 1
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define SIZEOF_LONG 8
#define SIZEOF_VOIDP 8
#define CURL_TYPEOF_CURL_OFF_T long
#define CURL_FORMAT_CURL_OFF_T "ld"
#define CURL_FORMAT_CURL_OFF_TU "lu"
#define CURL_FORMAT_OFF_T "%ld"
#define CURL_SIZEOF_CURL_OFF_T 8
#define CURL_SUFFIX_CURL_OFF_T L
#define CURL_SUFFIX_CURL_OFF_TU UL
